language: erlang
otp_release:
   - 20.0
   - 19.3
   - 19.2
   - 18.3
   - 18.2
   - 18.1
   - 18.0
   - 17.5
   - 17.1
   - R16B03-1
before_script:
   - kerl list installations
script: ./configure && make test
notifications:
   - email: benjamin.lee@realthought.net
